baseURL = 'https://avitg.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "anatole"
enableEmoji = true

[params]
title = "My New Hugo Site'"
author = "some Hugo Site"
description = "some hugo site"