baseURL = 'https://avitg.github.io/avitg'
languageCode = 'en-us'
title = 'My New Hugo Site'

#theme = "ace-documentation"
theme = "anatole"
enableEmoji = true

[params]
title = "My New Hugo Site'"
author = "some Hugo Site"
description = "some hugo site"
DefaultContentLanguage = "en"
mainSections = ["blog"]
profilePicture = "images/profile_pic.jpg"

contentDir = "content"


